### PR TITLE
Install CodeMirror plugin for page editing #631

### PR DESCRIPTION
**Pull request by DmitriyKartashov**
Implementation of task #631

Code ready for review.
Tested in IE 11, Google Chrome 41.0.2272.118, Firefox 37.0.2, Opera 29.0.

### CODE REVIEW

**Comment by amolenaar** [comment]
Nice patch! CodeMirror works pretty well. The colouring makes the wiki text more readable.

I have two suggestions:

1. I think `src/fitnesse/junit/JavaFormatter.java` doesn't need changing, since it only shows test results.
2. The CodeMirror editor could use a border, so it stands out more.

**Comment by DmitriyKartashov** [comment]
1. Fixed.
2. Partially fixed. I couldn't set up blue border with editor is focused. Is it critical?

Don't I need to do some work regarding licenses?

**Comment by amolenaar** [comment]
Thanks. I don't think we need to do anything regarding the license. It would be nice though to have a page explaining the components used along with their licenses.

**Comment by DmitriyKartashov** [comment]
Page was added. Please, review.

**Comment by amolenaar** [comment]
Nice, I'll find some time to merge this.

**Pull request merged**
