### PR TITLE
In-process Slim

### PR DESCRIPTION
**Pull request by amolenaar**
This PR makes Slim work really in-process (with the `&debug` option or when executed from JUnit). Previously a socket was opened to communicate between FitNesse and the SUT, although they were running in the same process. The socket has been replaced by a `MockSocket`.

### CODE REVIEW

**Comment by jplambert** [comment]
Hi,

I guess this is only for Java SUT? Or would it work with other Slim server implementations?

Thanks in advance.

**Comment by amolenaar** [comment]
Hi,

This only works for a Java SUT. The SUT needs to run on the JVM at least.

**Comment by jplambert** [comment]
That's what I thought.

I was asking because we are doing PHP and even though the Slim protocol over sockets provides a nice abstraction, in practice the PHP is always local and it would significantly improve the run time to avoid all the network stuff.

So far we thought that we could define a whole new Test System in FitNesse to do exactly that.

**Comment by amolenaar** [comment]
You can create your own test system, indeed.

I think using stdin/stdout instead of a socket would be a nice alternative.

**Pull request merged**
