### PR TITLE
New style wiki pages

### PR DESCRIPTION
**Pull request by amolenaar**
See #931 for rationale and discussion.

This PR introduces a new style for wiki page content.

Of course the old style pages can still be edited, they are not converted or something like that.

Pages can be renamed and moved. In both cases the pages are rewritten in the new file format.

If you really need the old file format, you can set the property `wiki.page.old.style` to `true`.
This will result in all pages being created as a directory with a `content.txt` and `properties.xml`.

### CODE REVIEW

**Comment by woodybrood** [comment]
So this is the big one? Is the recommendation that interested parties try it out before you merge, or will you merge and then get comments?

**Comment by jediwhale** [comment]
Nice!

**Comment by amolenaar** [comment]
Please try before merging, or merge it yourself if you're okay with this change. :)

**Comment by fhoeben** [comment]
I would like to have the option to 'bulk rewrite' an entire (sub-)wiki. That would allow me to ensure the entire test set is in one format. 

I would run this once (maybe by passing a special startup argument, e.g. `java -jar finesse-standalone.jar -convertPagesToNewWikiStyle`), and commit it as such in to version management. And know from then one there is only one page format for the entire test set. 

Would this be really hard to add (as you can already do a format change on move/rename)?

**Comment by amolenaar** [comment]
While on the topic, I do now know how (if at all) the user guide can be moved to the new format.

We do not want to change page types by default (since other tooling may depend on this format).

Would it be okay it if were possible from an IDE only?

**Comment by fhoeben** [comment]
IDE only (IntelliJ?) would be ok. But it would be nicer if it were just a call to make.

**Comment by kollaharsha** [comment]
Is there a way to convert all the existing pages into the new wiki page format from IDE (IntelliJ)?

**Comment by amolenaar** [comment]
I have not implemented that. For now the most convenient way is to move your test suite though the wiki.

**Comment by Johnny2Shoes** [comment]
For anyone else just stumbling upon this looking for why you can't get the new style wiki format to work on windows... it's because it requires Linux Style line endings (i.e. lf not crlf).

Add a .gitattributes file with `*.wiki text eol=lf ` to force git to sort this for you (or change your editor settings)

I was seeing this behaviour because of a slightly strange setup we are using but it may help someone else.

Cheers!

**Pull request merged**
