### PR TITLE
Don't use pipe via console on windows

### PR DESCRIPTION
**Pull request by fhoeben**
Prevent problems with multi byte characters when running slim tests on windows, issue #989

### CODE REVIEW

**Comment by fhoeben** [comment]
Fix prevents stack trace on Windows 10, but original problem did not occur there so not sure yet that this is full fix for #989

**Comment by fhoeben** [comment]
Checked this patch on Windows 7, issue #989 indeed no longer occurs.

**Comment by amolenaar** [comment]
If #997 works fine, I'd prefer that patch.

**Comment by six42** [comment]
I tested with WIndows 10 and Java 8 and have no problems: 
No Stack Trace 
and test with € is parsing.

Preventing pipes for Windows  is to radical.
Anybody who has problems with pipes  can just add to the root page
!define SLIM_PORT (8891) 
This will give back the default behaviour of the previous FitNesse version.
You can also define in the properties file 
slim.port =  8891
to get the same effect.

**Comment by fhoeben** [comment]
I believe the 'old behavior' was a random port, which was my workaround, using port '0' which selects a random port. Which is also the solution I use in this pull request.

One thing that is not clear to me: what is the advantage of not using a port?

**Comment by amolenaar** [comment]
One advantage is that there is no (re)cycling of ports, so you can run as many FitNesse instances as you like. This is a nice property of you're running your tests on CI for example.

**Comment by fhoeben** [comment]
I still see no problem using a random port in the ephemeral port range, but since defining `SLIM_PORT {0}` gets the same result I'll close this PR

**Pull request closed without merging**
