### PR TITLE
No links table

### PR DESCRIPTION
**Pull request by tcnh**
Support a Table type (prefix ^) that doesn't parse wikiwords, links and emailadresses.

Extended version of #1307, implementing the 'requirement' from #1308

### CODE REVIEW

**Comment by fhoeben** [comment]
Looks pretty good. We should probably add an acceptance test for the noLinks table.

Maybe we can prevent having to call `pluginsLoader.loadSymbolTypes()` twice (for each provider) by making the copy at a later point in time (i.e. after the plugins are loaded)? But on the other hand this approach allows a plugin to choose whether a symbol should be included in both providers, or only in one...

**Comment by tcnh** [comment]
What would a logical place for such an acceptance test be? I see no acceptance test for i.e. a literal table.

We could indeed copy at a later point to prevent the double administration, but I can imagine situations where one would want to exclude a custom symboltype from this table. I'd alway opt for more extensibility if the cost is not too high.

**Comment by jediwhale** [comment]
See FitNesse.SuiteAcceptanceTests.SuiteWidgetTests.TestTables - could add to this or make a new FitNesse.SuiteAcceptanceTests.SuiteWidgetTests.TestTablesNoLink

**Comment by tcnh** [comment]
Thanks! Added an acceptance test to that page

**Pull request merged**
