### PR TITLE
Make negative tests more readable

### PR DESCRIPTION
**Pull request by six42**
As a FitNesse developer
To test and see the behaviour of FitNesse with negative tests 
I run FitNesse in a sub instance 
and I need an easy way to see if the test did what I expected.

Added a scenario to extract the result of a single cell
Added a scenario to extract and match the result summary  
Added a scenario to show the result and input of a negativ test case in
HTML format
Added helper scenarios to hide the setup of the sub instance

### CODE REVIEW

**Comment by amolenaar** [comment]
This makes for a nice readability improvement. Is there a particular reason why you refactored those tests?

**Comment by amolenaar** [comment]
... only the tests fail now :( Any clue why? A short investigation on my side did not show a solution.

**Comment by six42** [comment]
strange, works nice for me.
Did you rebuild the Fitnesse-Standalone.jar and run the test with this?
The only thing I changed is removing the additional classpath elements.
can you send me the executionlog and testresult.xml?

**Comment by amolenaar** [comment]
I started FitNesse with `ant run`. Which class path elements did you remove? (I can't make it up from the changes).

**Comment by six42** [comment]
I will check once more with a clean build. Maybe I missed something.

**Comment by six42** [comment]
Now it works. 
The classpath was the issue. During junit testing the standalone.jar is not build and therefore the classpath to the classes folder is required.

**Comment by six42** [comment]
Closing as same code is also in #857.

**Pull request closed without merging**
