### PR TITLE
Add execution log to test history

### PR DESCRIPTION
**Pull request by amolenaar**
This PR lets FitNesse store the execution log (executed command, stdout, stderr) in the test history. This way the test execution log is always available (e.g. for analysis) along with the test results.

As a result ErrorLogs files are no longer created.

See #523.

### CODE REVIEW

**Comment by ranjith1882** [comment]
Hi,

I have updated with latest fitness version, after this upgrade, when I click on "Tests Executed OK" link to see execution log, an empty page is showing and i am not able to see any log info.

**Comment by amolenaar** [comment]
Hi, I checked, but was not able to reproduce. Does the same error happen when you execute a test from the FitNesse acceptance test suite?

**Comment by ranjith1882** [comment]
yes, same issue with fitnesse acceptance test suite also.

**Comment by ranjith1882** [comment]
Hey,

Its workinf fine, Issues is because of some template pages and css files are overrided in existing code base, replace with this version resource files and issue got resolved.

Thanks.

**Pull request merged**
