### PR TITLE
Fix encoding for pipe based socket

### LINKED ISSUE #989: Slim process dies without any error in log with FitNesse 20161106
I have a test, using Slim, which works with the previous version of 20160618. It also works with version 20161106 if I run it via jUnit using `FitNesseRunner` with Slim in-process. It does not work when started from the wiki (separate Java process for Slim), on Windows 7.

I just get a message that the communication with the Slim process was lost, and in the execution log I see no indication of what went wrong. The Slim process just seems to die, without any error output.
A part of the test is executed, the SuiteSetUp and SetUp, but Slim dies on the real test page. 
I've placed logging (to standard error) in my fixture code and I see that in the output of my SetUp pages, but the constructor of the fixture of the first (script) table never seems to be called. So I assume something happens in the code between the wiki and the Slim process before my fixture is even created.

I have no clue what the cause is, but processes stopping without any indication of what went wrong are very annoying....

### PR DESCRIPTION
**Pull request by amolenaar**
Should fix #989 and #995.

### CODE REVIEW

**Comment by amolenaar** [comment]
I have tried testing it on my Windows XP VM, but I can not reproduce the errors stated in #989.

I noticed, however, that the output streams on the Slim side do not apply the proper encoding (=UTF-8).

This PR should fix that. I hope someone can verify that (@fhoeben, @keetron)?

**Comment by fhoeben** [comment]
Unfortunately that does not fix the issue #989 on Windows 7.
It does fix the stack trace I encountered in the console on Windows 10, running Slim's multi-byte tests.

**Comment by amolenaar** [comment]
:(

**Comment by amolenaar** [comment]
Figured this change wouldn't hurt anyway.

**Pull request merged**
