### PR TITLE
add feature for plugin

### PR DESCRIPTION
**Pull request by youwi**
support plugin to handle response by url path.
so:
  http://localhost:8080/mypath/xxxxx/xxxx?yyyyy
  ---
  addResponder("/mypath/", MyResponder.class);
  ---
 do not support RegExp.
 this is a good idea for plugin.

### CODE REVIEW

**Comment by six42** [comment]
Hi youwi,
thanks for contributing.
Nice additional feature.
Could you provide a wiki test wich demonstrates why and how to use this feature.
look at the pages for the existing responders: http://fitnesse.org/FitNesse.SuiteAcceptanceTests.SuiteResponderTests
And can you update the responder factory overview page to mention this new feature:
http://fitnesse.org/FitNesse.UserGuide.AdministeringFitNesse.RestfulServices

**Comment by youwi** [comment]
maybe useless feature.
i use it with proxy. to aviod  cross-domain ajax.

http://localhost:8080/mypath/getUserInfo.rest ==>http://somehost/getUserInfo.rest

(somehost uncontrollable)

**Comment by six42** [comment]
Sounds rather sophisticated than useless.
What feature with Ajax did you added?

**Comment by youwi** [comment]
here is plan B .

**Comment by fhoeben** [comment]
I synced your branch with current master, and did a small cleanup of your code. I hope you don't mind.

I think this is ready to be merged as soon as you add some documentation. Maybe like @six42 suggested:

> And can you update the responder factory overview page to mention this new feature:
> FitNesse.UserGuide.AdministeringFitNesse.RestfulServices

**Pull request closed without merging**
