### PR TITLE
Feature to search method/scenario in pages.

### PR DESCRIPTION
**Pull request by suratdas**
Over a period of time, there will be a good number of methods/scenario written and used across teams. When it's time to clean-up/refactor those scenario, it's important to know where they are used to assess impact and plan.

image

### CODE REVIEW

**Comment by fhoeben** [comment]
To me this search seems a bit too limited (I prefer the full 'coverage' scan provided by the ['slimCoverage' test system in my plugin](https://github.com/fhoeben/hsac-fitnesse-plugin/blob/25aabda3f32e73a6776a996e70af203c3a8aa152/README.txt#L12), but I assume this search could have its value too).

To me it is not immediately clear what the 'Scope' radio buttons do. I assume they allow a subtree to be searched, if one navigates to the search page from a nested page. But in your screenshot I see 'All' and 'FitNesseRoot' which I assume both will mean all pages will be searched. In that situation I don't think we should show the scope radio, since the user's selection makes no difference.
I don't believe there are any tests to ensure the scope selection affects the search results. Can you add some?

**Comment by suratdas** [comment]
Thank you for your comment. I took the screenshot for "FitNesseRoot" but I tested using sub-suites. "FitNesseRoot" and "All"  will be displayed only if we initiate the search from "FitNesseRoot" page. This is the default behavior even for text and properties search. I added tests for scope selection result.

**Comment by fhoeben** [comment]
Can you add the new feature to the ReleaseNotes page also?

**Comment by suratdas** [comment]
Release notes updated. Thanks.

**Pull request merged**
